In [ ]:
# Run this cell first
!pip install praw psaw newsapi-python vaderSentiment transformers datasets sentence-transformers scikit-learn xgboost shap lime
# newspaper3k may need extra downloads (done later)

Collecting praw
  Downloading praw-7.8.1-py3-none-any.whl.metadata (9.4 kB)
Collecting psaw
  Downloading psaw-0.1.0-py3-none-any.whl.metadata (10 kB)
Collecting newsapi-python
  Downloading newsapi_python-0.2.7-py2.py3-none-any.whl.metadata (1.2 kB)
Collecting newspaper3k
  Downloading newspaper3k-0.2.8-py3-none-any.whl.metadata (11 kB)
Collecting vaderSentiment
  Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl.metadata (572 bytes)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.56.1)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.1.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (3.0.4)
Requirement already satisfied: shap in /usr/local/lib/python3.12/dist-packages (0.48.0)
Collecting lime
  Downloading lime-0.2.0.1.tar.gz (275 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 275.7/275.7 kB 4.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting prawcore<3,>=2.4 (from praw)
  Downloading prawcore-2.4.0-py3-none-any.whl.metadata (5.0 kB)
Collecting update_checker>=0.18 (from praw)
  Downloading update_checker-0.18.0-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: websocket-client>=0.54.0 in /usr/local/lib/python3.12/dist-packages (from praw) (1.8.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from psaw) (2.32.4)
Requirement already satisfied: Click in /usr/local/lib/python3.12/dist-packages (from psaw) (8.2.1)
Requirement already satisfied: beautifulsoup4>=4.4.1 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (4.13.5)
Requirement already satisfied: Pillow>=3.3.0 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (11.3.0)
Requirement already satisfied: PyYAML>=3.11 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (6.0.2)
Collecting cssselect>=0.9.2 (from newspaper3k)
  Downloading cssselect-1.3.0-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: lxml>=3.6.0 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (5.4.0)
Requirement already satisfied: nltk>=3.2.1 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (3.9.1)
Collecting feedparser>=5.2.1 (from newspaper3k)
  Downloading feedparser-6.0.12-py3-none-any.whl.metadata (2.7 kB)
Collecting tldextract>=2.0.1 (from newspaper3k)
  Downloading tldextract-5.3.0-py3-none-any.whl.metadata (11 kB)
Collecting feedfinder2>=0.0.4 (from newspaper3k)
  Downloading feedfinder2-0.0.4.tar.gz (3.3 kB)
  Preparing metadata (setup.py) ... done
Collecting jieba3k>=0.35.1 (from newspaper3k)
  Downloading jieba3k-0.35.1.zip (7.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.4/7.4 MB 85.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (2.9.0.post0)
Collecting tinysegmenter==0.3 (from newspaper3k)
  Downloading tinysegmenter-0.3.tar.gz (16 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.19.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.34.4)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (25.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.6.2)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.8.0+cu126)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.1)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.27.3)
Requirement already satisfied: slicer==0.0.8 in /usr/local/lib/python3.12/dist-packages (from shap) (0.0.8)
Requirement already satisfied: numba>=0.54 in /usr/local/lib/python3.12/dist-packages (from shap) (0.60.0)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from shap) (3.1.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from lime) (3.10.0)
Requirement already satisfied: scikit-image>=0.12 in /usr/local/lib/python3.12/dist-packages (from lime) (0.25.2)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.4.1->newspaper3k) (2.8)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from feedfinder2>=0.0.4->newspaper3k) (1.17.0)
Collecting sgmllib3k (from feedparser>=5.2.1->newspaper3k)
  Downloading sgmllib3k-1.0.0.tar.gz (5.8 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.12.15)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.1.9)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba>=0.54->shap) (0.43.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->psaw) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->psaw) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->psaw) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->psaw) (2025.8.3)
Requirement already satisfied: networkx>=3.0 in /usr/local/lib/python3.12/dist-packages (from scikit-image>=0.12->lime) (3.5)
Requirement already satisfied: imageio!=2.35.0,>=2.33 in /usr/local/lib/python3.12/dist-packages (from scikit-image>=0.12->lime) (2.37.0)
Requirement already satisfied: tifffile>=2022.8.12 in /usr/local/lib/python3.12/dist-packages (from scikit-image>=0.12->lime) (2025.8.28)
Requirement already satisfied: lazy-loader>=0.4 in /usr/local/lib/python3.12/dist-packages (from scikit-image>=0.12->lime) (0.4)
Collecting requests-file>=1.4 (from tldextract>=2.0.1->newspaper3k)
  Downloading requests_file-2.1.0-py2.py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.13.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (0.7.1)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.11.1.6)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->lime) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->lime) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->lime) (4.59.2)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->lime) (1.4.9)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->lime) (3.2.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.6.4)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.20.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.2)
Downloading praw-7.8.1-py3-none-any.whl (189 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 189.3/189.3 kB 16.1 MB/s eta 0:00:00
Downloading psaw-0.1.0-py3-none-any.whl (15 kB)
Downloading newsapi_python-0.2.7-py2.py3-none-any.whl (7.9 kB)
Downloading newspaper3k-0.2.8-py3-none-any.whl (211 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.1/211.1 kB 18.6 MB/s eta 0:00:00
Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl (125 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.0/126.0 kB 11.9 MB/s eta 0:00:00
Downloading cssselect-1.3.0-py3-none-any.whl (18 kB)
Downloading feedparser-6.0.12-py3-none-any.whl (81 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.5/81.5 kB 7.4 MB/s eta 0:00:00
Downloading prawcore-2.4.0-py3-none-any.whl (17 kB)
Downloading tldextract-5.3.0-py3-none-any.whl (107 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.4/107.4 kB 10.1 MB/s eta 0:00:00
Downloading update_checker-0.18.0-py3-none-any.whl (7.0 kB)
Downloading requests_file-2.1.0-py2.py3-none-any.whl (4.2 kB)
Building wheels for collected packages: tinysegmenter, lime, feedfinder2, jieba3k, sgmllib3k
  Building wheel for tinysegmenter (setup.py) ... done
  Created wheel for tinysegmenter: filename=tinysegmenter-0.3-py3-none-any.whl size=13540 sha256=67afbf811e353efe8bb7fdc131cf0d4ec91c12dea5c89611b1454ca280b56787
  Stored in directory: /root/.cache/pip/wheels/a5/91/9f/00d66475960891a64867914273fcaf78df6cb04d905b104a2a
  Building wheel for lime (setup.py) ... done
  Created wheel for lime: filename=lime-0.2.0.1-py3-none-any.whl size=283834 sha256=7eac67c89e93ab7cd991db91af80827ffd6f46149759aa3da0ad1013e4dcf965
  Stored in directory: /root/.cache/pip/wheels/e7/5d/0e/4b4fff9a47468fed5633211fb3b76d1db43fe806a17fb7486a
  Building wheel for feedfinder2 (setup.py) ... done
  Created wheel for feedfinder2: filename=feedfinder2-0.0.4-py3-none-any.whl size=3341 sha256=ad541770607dc44662a33435134b31abf6ae3a7461a5b3f3902648e6ae8abcff
  Stored in directory: /root/.cache/pip/wheels/9f/9f/fb/364871d7426d3cdd4d293dcf7e53d97f160c508b2ccf00cc79
  Building wheel for jieba3k (setup.py) ... done
  Created wheel for jieba3k: filename=jieba3k-0.35.1-py3-none-any.whl size=7398380 sha256=976fb6a34d177baf61c0a2ace77279f486a786b9f1d7aa6d1f07f8c73ed47f09
  Stored in directory: /root/.cache/pip/wheels/26/72/f7/fff392a8d4ea988dea4ccf9788599d09462a7f5e51e04f8a92
  Building wheel for sgmllib3k (setup.py) ... done
  Created wheel for sgmllib3k: filename=sgmllib3k-1.0.0-py3-none-any.whl size=6046 sha256=ee2f05e5d8d6baef6a4e86d5872b4a0fbecc316c045e960cfad822c34ea3530f
  Stored in directory: /root/.cache/pip/wheels/03/f5/1a/23761066dac1d0e8e683e5fdb27e12de53209d05a4a37e6246
Successfully built tinysegmenter lime feedfinder2 jieba3k sgmllib3k
Installing collected packages: tinysegmenter, sgmllib3k, jieba3k, feedparser, cssselect, vaderSentiment, update_checker, requests-file, psaw, prawcore, newsapi-python, feedfinder2, tldextract, praw, lime, newspaper3k
Successfully installed cssselect-1.3.0 feedfinder2-0.0.4 feedparser-6.0.12 jieba3k-0.35.1 lime-0.2.0.1 newsapi-python-0.2.7 newspaper3k-0.2.8 praw-7.8.1 prawcore-2.4.0 psaw-0.1.0 requests-file-2.1.0 sgmllib3k-1.0.0 tinysegmenter-0.3 tldextract-5.3.0 update_checker-0.18.0 vaderSentiment-3.3.2

In [ ]:
import os, re, json, time, math
import pandas as pd
import numpy as np
from datetime import datetime, timezone
import matplotlib.pyplot as plt
import joblib
from collections import Counter


# NLP
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# VADER
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

# scikit-learn
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

# HuggingFace pipeline (for inference)
from transformers import pipeline

# sentence-transformers
from sentence_transformers import SentenceTransformer

import praw
from psaw import PushshiftAPI

from newsapi import NewsApiClient

from transformers import AutoTokenizer, AutoModelForSequenceClassification, pipeline
import torch

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
path = "/content/drive/MyDrive/capstone"

In [ ]:
from google.colab import userdata
REDDIT_CLIENT_ID = userdata.get('REDDIT_CLIENT_ID')
REDDIT_CLIENT_SECRET = userdata.get('REDDIT_CLIENT_SECRET')
REDDIT_USER_AGENT = userdata.get('REDDIT_USER_AGENT')
NEWS_API_KEY = userdata.get("NEWS_API_KEY")

In [ ]:
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

In [ ]:
def clean_text(text):
    if not isinstance(text, str): return ""
    text = text.lower()
    text = re.sub(r'http\S+',' ', text)           # remove urls
    text = re.sub(r'@\w+',' ', text)              # twitter mentions
    text = re.sub(r'\$[A-Za-z]{1,6}\b',' ', text) # $TICKER
    text = re.sub(r'[^a-z0-9\s]',' ', text)       # keep alnum + spaces
    tokens = nltk.word_tokenize(text)
    tokens = [t for t in tokens if t not in stop_words and len(t)>1]
    tokens = [lemmatizer.lemmatize(t) for t in tokens]
    return " ".join(tokens)

In [ ]:
# crude ticker/company extractor: pass a list of tickers & company names you care about
def find_tickers(text, tickers_list, company_list=None):
    found = set()
    text_up = text.upper()
    # ticker forms: "TSLA", "$TSLA", "Tesla"
    for t in tickers_list:
        if re.search(r'\b' + re.escape(t.upper()) + r'\b', text_up):
            found.add(t.upper())
    if company_list:
        for name, t in company_list.items():
            if name.lower() in text.lower():
                found.add(t.upper())
    return list(found)

In [ ]:
reddit = praw.Reddit(client_id=REDDIT_CLIENT_ID,
                     client_secret=REDDIT_CLIENT_SECRET,
                     user_agent=REDDIT_USER_AGENT)

TECHNICAL SECTOR COMPANIES

In [ ]:
tickers = ["TSLA"]   # change to your portfolio
subs = []
start_epoch = int(datetime(2024,1,1).timestamp())
end_epoch   = int(datetime(2025,9,1).timestamp())

In [ ]:
def get_reddit_posts(keyword: str):
    """
    Fetch top Reddit posts from r/stocks, r/investing, r/wallstreetbets
    relevant to a keyword (last 1 year).
    """
    try:
        results = []
        subreddits = ["stocks", "investing", "wallstreetbets"]

        for sub in subreddits:
            subreddit = reddit.subreddit(sub)
            for post in subreddit.search(keyword, sort="relevance", time_filter="year", limit=50):
                text = (post.title or "") + " " + (post.selftext or "")
                results.append({
                    "id": post.id,
                    "created_utc": datetime.fromtimestamp(post.created_utc, tz=timezone.utc),
                    "subreddit": sub,
                    "score": post.score,
                    "num_comments": post.num_comments,
                    "title": post.title,
                    "body": post.selftext,
                    "url": f"https://www.reddit.com{post.permalink}",
                    "clean_text": clean_text(text)
                })

        return results if results else []

    except Exception as e:
        print(f"Error fetching Reddit posts: {str(e)}")
        return []

In [ ]:
all_subs = []
for t in tickers:
    posts = get_reddit_posts(t)
    if isinstance(posts, list):   # ensure it's not an error string
        all_subs.extend(posts)

# Convert to DataFrame
df_reddit = pd.DataFrame(all_subs)
print("reddit rows:", len(df_reddit))
print(df_reddit.head())

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

reddit rows: 150
        id               created_utc subreddit  score  num_comments  \
0  1nbo9zy 2025-09-08 13:50:34+00:00    stocks    745           161
1  1jfn3wn 2025-03-20 11:53:18+00:00    stocks  14663           666
2  1j9qzgg 2025-03-12 18:25:51+00:00    stocks   7231          1252
3  1j7l0bv 2025-03-09 23:35:58+00:00    stocks  18878           490
4  1jaciwt 2025-03-13 13:55:53+00:00    stocks   4267           494

                                               title  \
0                  TSLA to lose major revenue source
1  Tesla (TSLA) accounting raises red flags as re...
2                             TSLA investors, beware
3  TSLA being investigated by Transport Canada fo...
4  Tesla (TSLA) Stock: Trump’s Purchase Fails to ...

                                                body  \
0  Bloomberg is reporting that EV deregulation fr...
1  “Tesla’s (TSLA) accounting practices are raisi...
2  Trump's support of Tesla is a desperate and la...
3  The article notes that **four Tesla dealership...
4  Who knew that the publicity stunt on the WH la...

                                                 url  \
0  https://www.reddit.com/r/stocks/comments/1nbo9...
1  https://www.reddit.com/r/stocks/comments/1jfn3...
2  https://www.reddit.com/r/stocks/comments/1j9qz...
3  https://www.reddit.com/r/stocks/comments/1j7l0...
4  https://www.reddit.com/r/stocks/comments/1jaci...

                                          clean_text
0  tsla lose major revenue source bloomberg repor...
1  tesla tsla accounting raise red flag report sh...
2  tsla investor beware trump support tesla despe...
3  tsla investigated transport canada cooking boo...
4  tesla tsla stock trump purchase fails sustain ...

In [ ]:
df_reddit

,id,created_utc,subreddit,score,num_comments,title,body,url,clean_text
0,1nbo9zy,2025-09-08 13:50:34+00:00,stocks,745,161,TSLA to lose major revenue source,Bloomberg is reporting that EV deregulation fr...,https://www.reddit.com/r/stocks/comments/1nbo9...,tsla lose major revenue source bloomberg repor...
1,1jfn3wn,2025-03-20 11:53:18+00:00,stocks,14663,666,Tesla (TSLA) accounting raises red flags as re...,“Tesla’s (TSLA) accounting practices are raisi...,https://www.reddit.com/r/stocks/comments/1jfn3...,tesla tsla accounting raise red flag report sh...
2,1j9qzgg,2025-03-12 18:25:51+00:00,stocks,7231,1252,"TSLA investors, beware",Trump's support of Tesla is a desperate and la...,https://www.reddit.com/r/stocks/comments/1j9qz...,tsla investor beware trump support tesla despe...
3,1j7l0bv,2025-03-09 23:35:58+00:00,stocks,18878,490,TSLA being investigated by Transport Canada fo...,The article notes that **four Tesla dealership...,https://www.reddit.com/r/stocks/comments/1j7l0...,tsla investigated transport canada cooking boo...
4,1jaciwt,2025-03-13 13:55:53+00:00,stocks,4267,494,Tesla (TSLA) Stock: Trump’s Purchase Fails to ...,Who knew that the publicity stunt on the WH la...,https://www.reddit.com/r/stocks/comments/1jaci...,tesla tsla stock trump purchase fails sustain ...
...,...,...,...,...,...,...,...,...,...
145,1hbzq72,2024-12-11 18:05:13+00:00,wallstreetbets,1208,99,TSLA 💎 Hands 950%,Held through ATH to 100s back to ATH,https://www.reddit.com/r/wallstreetbets/commen...,tsla hand 950 held ath 100 back ath
146,1fuhafq,2024-10-02 14:18:37+00:00,wallstreetbets,388,407,$98k YOLO on $TSLA 10/18 calls. Tesla is going...,Not financial advice,https://www.reddit.com/r/wallstreetbets/commen...,98k yolo 10 18 call tesla going print cybercab...
147,1gp6tf7,2024-11-11 23:38:58+00:00,wallstreetbets,957,123,$TSLA Calls Closed +$400k,Haven't gotten any sleep holding these Tesla c...,https://www.reddit.com/r/wallstreetbets/commen...,call closed 400k gotten sleep holding tesla ca...
148,1k5ltx6,2025-04-23 00:17:43+00:00,wallstreetbets,26572,1641,THIS CASINO IS RIGGED!,EARNING MISSED BY WHOPPING 35%? TSLA IS UP!!!!...,https://www.reddit.com/r/wallstreetbets/commen...,casino rigged earning missed whopping 35 tsla ...
149,1j8s8z4,2025-03-11 14:38:07+00:00,wallstreetbets,722,104,"Feels good to be a TSLA 🌈🐻. $20,000 gain buyin...",Did I nearly full port for a 32% gain? Yes. Wo...,https://www.reddit.com/r/wallstreetbets/commen...,feel good tsla 20 000 gain buying 30 min marke...

In [ ]:
def get_market_news_df(query: str) -> pd.DataFrame:
    """
    Fetch the most relevant business/finance news about a company or sector.
    Returns a DataFrame with title, url, publishedAt, and source.
    """
    try:
        if not NEWS_API_KEY:
            return pd.DataFrame([{"error": "NEWS_API_KEY not set in environment"}])

        newsapi = NewsApiClient(api_key=NEWS_API_KEY)

        # Fetch relevant articles
        articles = newsapi.get_everything(
            q=query,
            language="en",
            sort_by="publishedAt"
        )

        if not articles["articles"]:
            return pd.DataFrame([{"error": f"No news found for {query}"}])

        # Build DataFrame
        df = pd.DataFrame([{
            "title": a["title"],
            "url": a["url"],
            "publishedAt": a["publishedAt"],
            "source": a["source"]["name"]
        } for a in articles["articles"][:10]])

        return df

    except Exception as e:
        return pd.DataFrame([{"error": str(e)}])

In [ ]:
df_news = get_market_news_df("Tesla")
print("rows:", len(df_news))
df_news.head()

rows: 10

,title,url,publishedAt,source
0,Top Large Cap Stocks To Follow Now – September...,https://www.etfdailynews.com/2025/09/12/top-la...,2025-09-12T12:30:46Z,ETF Daily News
1,Could Elon Musk Buy Verizon? He Says It’s Poss...,https://www.androidheadlines.com/2025/09/could...,2025-09-12T12:20:25Z,Android Headlines
2,CHTR SECURITIES NOTICE: Did Charter Communicat...,https://www.globenewswire.com/news-release/202...,2025-09-12T12:18:00Z,GlobeNewswire
3,"RXST SECURITIES NOTICE: Did RxSight, Inc. Misl...",https://www.globenewswire.com/news-release/202...,2025-09-12T12:18:00Z,GlobeNewswire
4,"SLP SECURITIES NOTICE: Did Simulations Plus, I...",https://www.globenewswire.com/news-release/202...,2025-09-12T12:18:00Z,GlobeNewswire

In [ ]:
# --- Reddit prep ---
if not df_reddit.empty:
    df_reddit['source'] = 'reddit'
    df_reddit['date'] = pd.to_datetime(df_reddit['created_utc'], unit='s').dt.date
    df_reddit['text'] = df_reddit['title'].fillna('') + " " + df_reddit.get('body', '').fillna('')
    df_reddit['score'] = df_reddit.get('score', 0)
    df_reddit['num_comments'] = df_reddit.get('num_comments', 0)
    df_reddit['clean_text'] = df_reddit['text'].apply(clean_text)
else:
    df_reddit = pd.DataFrame(columns=['source','date','text','clean_text','score','num_comments'])

# --- News prep ---
if not df_news.empty and "error" not in df_news.columns:
    df_news['source'] = 'news'
    df_news['date'] = pd.to_datetime(df_news['publishedAt']).dt.date
    df_news['text'] = df_news['title'].fillna('')
    df_news['score'] = None
    df_news['num_comments'] = None
    df_news['clean_text'] = df_news['text'].apply(clean_text)
else:
    df_news = pd.DataFrame(columns=['source','date','text','clean_text','score','num_comments'])

# --- Merge all ---
df_all = pd.concat([df_reddit[['source','date','text','clean_text','score','num_comments']],
                    df_news[['source','date','text','clean_text','score','num_comments']]],
                   ignore_index=True, sort=False)

# shuffle rows
df_all = df_all.sample(frac=1, random_state=42).reset_index(drop=True)

print("Merged dataset rows:", len(df_all))
df_all.head()

Merged dataset rows: 160

,source,date,text,clean_text,score,num_comments
0,reddit,2025-05-09,LFG!!!!! TSLA this morning GOT ME INTO 6 FIGUR...,lfg tsla morning got figure insane month tradi...,3243,857
1,reddit,2025-03-25,"Stop buying $TSLA puts Hello Regard,\n\nI have...",stop buying put hello regard consistently buyi...,4284,429
2,reddit,2025-01-18,I Paper Handed My Way Out of Scoring Nearly $2...,paper handed way scoring nearly 200k tsla put ...,730,197
3,reddit,2025-02-07,Chinese Markets are Rejecting Tesla China Is M...,chinese market rejecting tesla china moving te...,1797,312
4,reddit,2025-06-21,Stocks to hold 5-10 years I’m looking for stoc...,stock hold 10 year looking stock hold 10 year ...,0,89

In [ ]:
os.makedirs(path, exist_ok=True)

# File path
merged_file = os.path.join(path, "merged_reddit_news.parquet")

# Save
df_all.to_parquet(merged_file, index=False)
print(f"Merged dataset saved → {merged_file}")

Merged dataset saved → /content/drive/MyDrive/capstone/merged_reddit_news.parquet

In [ ]:
if os.path.exists(merged_file):
    df_all = pd.read_parquet(merged_file)
    print(f"Loaded {len(df_all)} rows from {merged_file}")
else:
    print("File not found:", merged_file)

Loaded 160 rows from /content/drive/MyDrive/capstone/merged_reddit_news.parquet

In [ ]:
df_all2 = df_all.copy()

In [ ]:
analyzer = SentimentIntensityAnalyzer()
df_all['vader_compound'] = df_all['clean_text'].apply(lambda t: analyzer.polarity_scores(t)['compound'])
# simple labels from vader
df_all['vader_label'] = df_all['vader_compound'].apply(lambda s: 'pos' if s>=0.05 else ('neg' if s<=-0.05 else 'neu'))

# Finance note: VADER is tuned for social media — for financial text consider FinBERT or Loughran-McDonald lexicon.
print(df_all['vader_label'].value_counts())
df_all.head()

vader_label
pos    98
neg    41
neu    21
Name: count, dtype: int64

,source,date,text,clean_text,score,num_comments,vader_compound,vader_label
0,reddit,2025-05-09,LFG!!!!! TSLA this morning GOT ME INTO 6 FIGUR...,lfg tsla morning got figure insane month tradi...,3243.0,857.0,-0.9118,neg
1,reddit,2025-03-25,"Stop buying $TSLA puts Hello Regard,\n\nI have...",stop buying put hello regard consistently buyi...,4284.0,429.0,-0.9578,neg
2,reddit,2025-01-18,I Paper Handed My Way Out of Scoring Nearly $2...,paper handed way scoring nearly 200k tsla put ...,730.0,197.0,-0.7645,neg
3,reddit,2025-02-07,Chinese Markets are Rejecting Tesla China Is M...,chinese market rejecting tesla china moving te...,1797.0,312.0,0.7569,pos
4,reddit,2025-06-21,Stocks to hold 5-10 years I’m looking for stoc...,stock hold 10 year looking stock hold 10 year ...,0.0,89.0,0.8126,pos

In [ ]:
# Baseline: use VADER labels as weak labels
df_train = df_all[df_all['vader_label'].isin(['pos','neg'])].copy()  # remove neutral for binary
X = df_train['clean_text']
y = df_train['vader_label']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# TF-IDF
vect = TfidfVectorizer(ngram_range=(1,2), max_features=20000)
X_train_vec = vect.fit_transform(X_train)
X_test_vec = vect.transform(X_test)

# Logistic Regression
clf = LogisticRegression(max_iter=1000, class_weight='balanced')
clf.fit(X_train_vec, y_train)

# Evaluate
y_pred = clf.predict(X_test_vec)
print(classification_report(y_test, y_pred))

joblib.dump(clf, os.path.join(path, "sentiment_model.pkl"))
joblib.dump(vect, os.path.join(path, "tfidf_vectorizer.pkl"))

print(f"Model + vectorizer saved → {path}")

              precision    recall  f1-score   support

         neg       0.50      0.12      0.20         8
         pos       0.73      0.95      0.83        20

    accuracy                           0.71        28
   macro avg       0.62      0.54      0.51        28
weighted avg       0.66      0.71      0.65        28

Model + vectorizer saved → /content/drive/MyDrive/capstone

In [ ]:
# Load FinBERT (pretrained on financial text)
model_name = "yiyanghkust/finbert-tone"  # popular FinBERT model for finance sentiment
finbert_pipe = pipeline(
    "sentiment-analysis",
    model=model_name,
    tokenizer=model_name,
    device=0 if torch.cuda.is_available() else -1  # GPU if available
)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/533 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/439M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/439M [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

Device set to use cpu

In [ ]:
# Helper function to get label + score
def finbert_sentiment(text):
    # truncate long text
    out = finbert_pipe(text[:512])[0]
    # output format: {'label': 'positive', 'score': 0.99}
    return out['label'].lower(), out['score']

In [ ]:
df_all['finbert_label_score'] = df_all['clean_text'].apply(lambda t: finbert_sentiment(t))
df_all[['finbert_label','finbert_score']] = pd.DataFrame(df_all['finbert_label_score'].tolist(), index=df_all.index)
df_all.drop(columns=['finbert_label_score'], inplace=True)

# Check
df_all[['text','finbert_label','finbert_score']].head()

,text,finbert_label,finbert_score
0,LFG!!!!! TSLA this morning GOT ME INTO 6 FIGUR...,neutral,1.000000
1,"Stop buying $TSLA puts Hello Regard,\n\nI have...",neutral,0.737032
2,I Paper Handed My Way Out of Scoring Nearly $2...,neutral,0.908910
3,Chinese Markets are Rejecting Tesla China Is M...,positive,0.955875
4,Stocks to hold 5-10 years I’m looking for stoc...,positive,1.000000

In [ ]:
# Count FinBERT sentiment distribution
print(df_all['finbert_label'].value_counts())

# If you want it neatly formatted
print("\nFinBERT Sentiment Counts:")
for label, count in df_all['finbert_label'].value_counts().items():
    print(f"{label}    {count}")

finbert_label
neutral     89
positive    40
negative    31
Name: count, dtype: int64

FinBERT Sentiment Counts:
neutral    89
positive    40
negative    31

In [ ]:
def top_tfidf_ngrams(docs, top_k=20):
    vect = TfidfVectorizer(ngram_range=(1,2), stop_words='english', max_features=5000)
    X = vect.fit_transform(docs)
    means = np.array(X.mean(axis=0)).ravel()
    top = sorted(zip(vect.get_feature_names_out(), means), key=lambda x: x[1], reverse=True)[:top_k]
    return [w for w, _ in top]

# Split docs by FinBERT label
pos_docs = df_all[df_all['finbert_label']=='positive']['clean_text'].astype(str)
neg_docs = df_all[df_all['finbert_label']=='negative']['clean_text'].astype(str)
neu_docs = df_all[df_all['finbert_label']=='neutral']['clean_text'].astype(str)

# Run for each FinBERT label
pos_top = top_tfidf_ngrams(pos_docs, 20)
neg_top = top_tfidf_ngrams(neg_docs, 20)
neu_top = top_tfidf_ngrams(neu_docs, 20)

# Print as clean lists
print("\nTop Positive ngrams:", pos_top)
print("\nTop Negative ngrams:", neg_top)
print("\nTop Neutral ngrams:", neu_top)

Top Positive ngrams: ['tesla', 'tsla', 'stock', 'year', 'market', 'price', 'best', 'elon', 'china', 'musk', 'buy', 'company', 'ai', '10', 'growth', 'long', 'going', 'gain', '10 year', 'think']

Top Negative ngrams: ['tesla', 'tsla', 'stock', 'investment', 'bfa', 'bfa law', 'contact', 'contact bfa', 'investor contact', 'law', 'law lost', 'mislead', 'mislead investor', 'money investment', 'security', 'security notice', 'lost', 'musk', 'investor', 'money']

Top Neutral ngrams: ['tsla', 'tesla', 'stock', 'year', 'elon', 'musk', 'company', 'buy', 'market', 'trump', '000', 'going', 'money', 'time', 'like', 'today', 'bought', '10', 'share', 'day']

In [ ]:
def top_features_by_class(vectorizer, clf, top_n=20):
    feature_names = np.array(vectorizer.get_feature_names_out())
    coefs = clf.coef_[0]

    # Top positive n-grams
    top_pos_idx = np.argsort(coefs)[-top_n:]
    top_pos = feature_names[top_pos_idx][::-1]

    # Top negative n-grams
    top_neg_idx = np.argsort(coefs)[:top_n]
    top_neg = feature_names[top_neg_idx]

    return list(top_pos), list(top_neg)

top_pos, top_neg = top_features_by_class(vect, clf, top_n=20)

print("Top Positive ngrams:", top_pos)
print("Top Negative ngrams:", top_neg)

Top Positive ngrams: ['year', '000', 'elon musk', 'company', 'term', 'yolo', 'growth', 'share', 'best', 'amazon', 'top', 'close', 'long', 'profit', '10', 'bear', 'yield', 'brkb', 'rivian', 'meta']
Top Negative ngrams: ['put', 'regret', 'canada', 'stupid bought', 'bought tsla', 'trump', 'early', 'stupid', 'tsla', 'bought', '250', 'selling', 'rebate', 'earning', 'regret selling', 'tsmc', 'ceo', 'reddit', '00', '400 call']

In [ ]:
# Simple tokenizer
def tokenize(text):
    return re.findall(r'\b\w+\b', text.lower())

# Function to get top n tokens per sentiment
def get_top_ngrams_by_sentiment(df, label, n=20):
    texts = df[df['vader_label'] == label]['clean_text']
    tokens = []
    for txt in texts:
        tokens.extend(tokenize(txt))
    counter = Counter(tokens)
    return [w for w, _ in counter.most_common(n)]

# Print top ngrams
print("Top Positive ngrams:", get_top_ngrams_by_sentiment(df_all, "pos"))
print("Top Negative ngrams:", get_top_ngrams_by_sentiment(df_all, "neg"))
print("Top Neutral ngrams:", get_top_ngrams_by_sentiment(df_all, "neu"))

Top Positive ngrams: ['tesla', 'year', 'tsla', 'stock', 'market', 'company', '10', 'like', 'musk', 'time', 'elon', 'share', 'long', 'buy', 'price', 'would', 'going', 'term', 'bond', 'yield']
Top Negative ngrams: ['tsla', 'tesla', 'stock', 'trump', 'put', 'tariff', 'u', 'elon', 'said', 'musk', 'canada', 'one', 'would', 'market', 'trade', 'time', 'going', 'china', 'even', 'still']
Top Neutral ngrams: ['money', 'lost', 'tsla', 'investment', 'security', 'notice', 'mislead', 'investor', 'contact', 'bfa', 'law', 'today', 'year', 'inc', 'vehicle', 'musk', 'tesla', 'delivery', 'put', 'stock']

In [ ]:
# 1. Logistic Regression (already trained)
y_pred_lr = clf.predict(X_test_vec)
print("Logistic Regression Report:")
print(classification_report(y_test, y_pred_lr))

Logistic Regression Report:
              precision    recall  f1-score   support

         neg       0.50      0.12      0.20         8
         pos       0.73      0.95      0.83        20

    accuracy                           0.71        28
   macro avg       0.62      0.54      0.51        28
weighted avg       0.66      0.71      0.65        28

# Model comparison and reasoning — VADER vs LogisticRegression vs FinBERT

**Summary of what we did**
- We scored the same TSLA dataset with three approaches:
  1. **VADER** — a rule/lexicon-based social-media tuned scorer (fast, no training).
  2. **Logistic Regression + TF-IDF** — trained on Financial PhraseBank (phrasebank) as a lightweight, explainable ML model.
  3. **FinBERT** — a finance-domain transformer (strong out-of-the-box financial understanding).

**Observed behavior**  
- **Logistic Regression**: performs *well* on formal, news-like sentences. It is fast, interpretable, and easy to export & run. It **learns the patterns from labeled financial text**, but will underperform on very informal social-media language unless we augment training data.
- **VADER**: quick baseline for social text, but **too noisy for finance** and often confuses domain-specific terms (e.g., “dilution”, “guidance”) or sarcasm. Good for sanity checks, not final signals.
- **FinBERT**: strong, domain-tuned transformer that captures finance nuance better than VADER or a TF-IDF model trained on limited data. Downsides: heavier (latency, GPU/CPU cost), less interpretable, and in some settings there may be constraints around directly using such large transformer models.

Now we use **Logistic Regression (trained on Financial PhraseBank)** as the primary model for **news/article** sentiment: it’s fast, explainable, and easy to ship in a microservice or agent.

**TRAINING LOGISTIC REGRESSION ON PHRASE BANK**

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/capstone/financialData.csv", encoding='latin-1')

In [ ]:
# Rename columns to 'text' and 'sentiment' based on the file content
df = df.rename(columns={
    'neutral': 'sentiment',
    'According to Gran , the company has no plans to move all production to Russia , although that is where the company is growing .': 'text'
})

df = df[['text', 'sentiment']]  # keep only relevant columns
df.head()

                                                text sentiment
0  Technopolis plans to develop in stages an area...   neutral
1  The international electronic industry company ...  negative
2  With the new production plant the company woul...  positive
3  According to the company 's updated strategy f...  positive
4  FINANCING OF ASPOCOMP 'S GROWTH Aspocomp is ag...  positive

In [ ]:
df2 = df.copy()

In [ ]:
df_train = df[df['sentiment'].isin(['positive','negative'])].copy()

X = df_train['text']
y = df_train['sentiment'].str.lower()  # convert to 'pos'/'neg'

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [ ]:
# TF-IDF vectorization
vect = TfidfVectorizer(ngram_range=(1,2), max_features=20000)
X_train_vec = vect.fit_transform(X_train)
X_test_vec = vect.transform(X_test)

# Logistic Regression
clf = LogisticRegression(max_iter=1000, class_weight='balanced')
clf.fit(X_train_vec, y_train)

# Evaluate
y_pred = clf.predict(X_test_vec)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

    negative       0.77      0.76      0.77       121
    positive       0.89      0.90      0.90       273

    accuracy                           0.86       394
   macro avg       0.83      0.83      0.83       394
weighted avg       0.86      0.86      0.86       394

In [ ]:
joblib.dump(clf, "/content/logreg_sentiment.pkl")
joblib.dump(vect, "/content/tfidf_vectorizer2.pkl")
print("Model and vectorizer saved!")

Model and vectorizer saved!

In [ ]:
article_text = "TSLA to lose major revenue source"

# Transform text into TF-IDF features
X_new_vec = vect.transform([article_text])

# Predict sentiment
predicted_sentiment = clf.predict(X_new_vec)[0]
print(f"Predicted sentiment: {predicted_sentiment}")

Predicted sentiment: positive

In [ ]:
article_text = "TSLA being investigated by Transport Canada for cooking their books in Canada to snag EV rebates without selling cars"

# Transform text into TF-IDF features
X_new_vec = vect.transform([article_text])

# Predict sentiment
predicted_sentiment = clf.predict(X_new_vec)[0]
print(f"Predicted sentiment: {predicted_sentiment}")

Predicted sentiment: positive

In [ ]:
article_text = "Tesla (TSLA) accounting raises red flags as report shows $1.4 billion missing"

# Transform text into TF-IDF features
X_new_vec = vect.transform([article_text])

# Predict sentiment
predicted_sentiment = clf.predict(X_new_vec)[0]
print(f"Predicted sentiment: {predicted_sentiment}")

Predicted sentiment: negative

In [ ]:
sentence = "TSLA to lose major revenue source"

# Use your FinBERT helper
label, score = finbert_sentiment(sentence)

print(f"Sentence: {sentence}")
print(f"Predicted Sentiment: {label}, Confidence: {score:.2f}")

Sentence: TSLA being investigated by Transport Canada for cooking their books in Canada to snag EV rebates without selling cars.
Predicted Sentiment: neutral, Confidence: 1.00

In [ ]:
sentence = "TSLA being investigated by Transport Canada for cooking their books in Canada to snag EV rebates without selling cars"

# Use your FinBERT helper
label, score = finbert_sentiment(sentence)

print(f"Sentence: {sentence}")
print(f"Predicted Sentiment: {label}, Confidence: {score:.2f}")

Sentence: TSLA being investigated by Transport Canada for cooking their books in Canada to snag EV rebates without selling cars
Predicted Sentiment: neutral, Confidence: 0.99

In [ ]:
sentence = "Tesla (TSLA) accounting raises red flags as report shows $1.4 billion missing"

# Use your FinBERT helper
label, score = finbert_sentiment(sentence)

print(f"Sentence: {sentence}")
print(f"Predicted Sentiment: {label}, Confidence: {score:.2f}")

Sentence: Tesla (TSLA) accounting raises red flags as report shows $1.4 billion missing
Predicted Sentiment: positive, Confidence: 0.46

In [ ]:
df_reddit['title'][1]

'Tesla (TSLA) accounting raises red flags as report shows $1.4 billion missing'